### ISSUE TITLE
Can you tell me how to set up the BIOS?

### ISSUE THREAD

**Issue by zhuwenhu14** [JoveYu/ASUS-TUF-GAMING-B560M-PLUS-WIFI-EFI#1]
Can you tell me how to set up the BIOS? iam 11600k+B560M TUF GAMING  WIFI

**Comment by JoveYu** [comment]
主要就是一些常用的关闭项，大概回忆了下，关闭
```
Boot -- Fast Boot -> Disabled
Boot -- Secure Boot -- OS Type -- Other OS
Boot -- CSM(Compatibility Support Module) -> Disabled
```

我用10代CPU， 苹果目前没有11代的设备，目前mac默认是无法支持11代CPU的，需要仿冒CPU，你可以查询下教程

**Comment by zhuwenhu14** [comment]
> 主要就是一些常用的关闭项，大概回忆了下，关闭
> 
> ```
> Boot -- Fast Boot -> Disabled
> Boot -- Secure Boot -- OS Type -- Other OS
> Boot -- CSM(Compatibility Support Module) -> Disabled
> ```
> 
> 我用10代CPU，苹果目前没有11代的设备，目前mac替代是无法支持11代CPU的，需要仿冒CPU，你可以查询下教程

哦哦！原来中文可以，我还以为需要英文，我就是按照您这样子设置的，但是还是不行，可能是需要仿冒吧，看来我只有等了，我对这个不是太懂！

**Comment by Endless1218** [comment]
DP接口引导的时候黑屏，有解决办法吗

**Comment by JoveYu** [comment]
我使用rx580  DP口一切正常  你说的不太清楚

**Comment by zhuwenhu14** [comment]
> DP接口引导的时候黑屏，有解决办法吗

DP您是用的核显么？你试试禁用BIOS独显，具体你百度一下，应该可以解决！

**Comment by w43322** [comment]
仿冒的话仿冒10代或者9代都可以，我用的qv1j一切正常。

**Comment by ChenZesen** [comment]
> 主要就是一些常用的关闭项，大概回忆了下，关闭
> 
> ```
> Boot -- Fast Boot -> Disabled
> Boot -- Secure Boot -- OS Type -- Other OS
> Boot -- CSM(Compatibility Support Module) -> Disabled
> ```
> 
> 我用10代CPU， 苹果目前没有11代的设备，目前mac默认是无法支持11代CPU的，需要仿冒CPU，你可以查询下教程

有没有定制usb

**Comment by chhuax** [comment]
是不是可以写一下使用说明和其他的硬件信息，感谢

**Comment by kaiYuan-code** [comment]
> 仿冒的话仿冒10代或者9代都可以，我用的qv1j一切正常。

请问具体是如何仿冒的呢

**Comment by w43322** [comment]
> > 仿冒的话仿冒10代或者9代都可以，我用的qv1j一切正常。
> 
> 请问具体是如何仿冒的呢

opencore配置中覆盖一下cpuid
