### ISSUE TITLE
About Framebuffer patch

### ISSUE THREAD

**Issue by drmacman** [JoveYu/ASUS-TUF-GAMING-B560M-PLUS-WIFI-EFI#2]
There is no Framebuffer patch in DeviceProperties... Can you boot macOS with this EFI?
I tried with this EFI but won't boot.

**Comment by JoveYu** [comment]
I use rx580 with 10400F

**Comment by drmacman** [comment]
I see, thanks!

**Comment by drmacman** [comment]
Have you edited AML(s) which is  related to graphics?
